table 'Fairway Log'
	lineageTag: 6e99cbd4-3491-47c2-858e-e16b91b63218

	measure MissLeft% = ```
			
			VAR _val =
			    DIVIDE (
			        COUNTROWS ( FILTER ( 'Fairway Log', 'Fairway Log'[Fairway Score] = "←" ) ),
			        COUNTROWS ( FILTER ( 'Fairway Log', NOT ( ISBLANK ( 'Fairway Log'[Fairway Score] ) ) ) )
			    )
			RETURN
			IF ( ISBLANK ( _val ), "N/A", FORMAT ( _val, "0.0%" ) )
			
			```
		lineageTag: c70d9d8a-0bad-4b85-8de7-a947aeb06c5f

	measure MissRight% = ```
			
			VAR _val =
			    DIVIDE (
			        COUNTROWS ( FILTER ( 'Fairway Log', 'Fairway Log'[Fairway Score] = "→" ) ),
			        COUNTROWS ( FILTER ( 'Fairway Log', NOT ( ISBLANK ( 'Fairway Log'[Fairway Score] ) ) ) )
			    )
			RETURN
			IF ( ISBLANK ( _val ), "N/A", FORMAT ( _val, "0.0%" ) )
			
			```
		lineageTag: bc873ccd-8eff-44a8-a8c4-2ad811df173f

	measure MissShort% = ```
			
			VAR _val =
			    DIVIDE (
			        COUNTROWS ( FILTER ( 'Fairway Log', 'Fairway Log'[Fairway Score] = "↓" ) ),
			        COUNTROWS ( FILTER ( 'Fairway Log', NOT ( ISBLANK ( 'Fairway Log'[Fairway Score] ) ) ) )
			    )
			RETURN
			IF ( ISBLANK ( _val ), "N/A", FORMAT ( _val, "0.0%" ) )
			
			```
		lineageTag: 0adbbdc0-6279-4d2c-a862-817925bcbefb

	measure MissLong% = ```
			
			VAR _val =
			    DIVIDE (
			        COUNTROWS ( FILTER ( 'Fairway Log', 'Fairway Log'[Fairway Score] = "↑" ) ),
			        COUNTROWS ( FILTER ( 'Fairway Log', NOT ( ISBLANK ( 'Fairway Log'[Fairway Score] ) ) ) )
			    )
			RETURN
			IF ( ISBLANK ( _val ), "N/A", FORMAT ( _val, "0.0%" ) )
			
			```
		lineageTag: 4af11906-e96c-4f2b-a00f-269b0a324efb

	measure HitCenter% = ```
			
			VAR _val =
			    DIVIDE (
			        COUNTROWS ( FILTER ( 'Fairway Log', 'Fairway Log'[Fairway Score] IN { "✓", "1" } ) ),
			        COUNTROWS ( FILTER ( 'Fairway Log', NOT ( ISBLANK ( 'Fairway Log'[Fairway Score] ) ) ) )
			    )
			RETURN
			IF ( ISBLANK ( _val ), "N/A", FORMAT ( _val, "0.0%" ) )
			
			```
		lineageTag: 78fb2b26-a0a7-449f-9371-15290c793ee4

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fc9b3d3a-b526-4a08-afcd-426a3a3eed57
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 1bb163fa-69f3-4313-993a-51557150d50c
			defaultHierarchy: LocalDateTable_23b67ad6-a713-4f4e-ab04-2442997e7aea.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Course
		dataType: string
		lineageTag: fafeec54-3149-4379-a215-8e95516a6db4
		summarizeBy: none
		sourceColumn: Course

		annotation SummarizationSetBy = Automatic

	column Fairways
		dataType: int64
		formatString: 0
		lineageTag: 6798b80e-1085-4fa3-b9bb-f53d2689b989
		summarizeBy: none
		sourceColumn: Fairways

		annotation SummarizationSetBy = User

	column Hole
		dataType: string
		lineageTag: 54c8a7f8-5b3c-446e-b318-fb7127ab5345
		summarizeBy: none
		sourceColumn: Hole

		annotation SummarizationSetBy = Automatic

	column 'Fairway Score'
		dataType: string
		lineageTag: 22ab8e82-3376-40ad-bac8-a0b710b8b499
		summarizeBy: none
		sourceColumn: Fairway Score

		annotation SummarizationSetBy = Automatic

	column CourseHoleKey
		dataType: string
		lineageTag: a0595f18-c587-457f-b650-a5f120adb8f0
		summarizeBy: none
		sourceColumn: CourseHoleKey

		annotation SummarizationSetBy = Automatic

	column RoundKey
		dataType: string
		lineageTag: 42f9551d-39aa-4fb7-b1dd-9087dbfbea22
		summarizeBy: none
		sourceColumn: RoundKey

		annotation SummarizationSetBy = Automatic

	column 'Short Course'
		dataType: string
		lineageTag: cb7c8434-dc67-4b98-9c57-7d9f10a270fc
		summarizeBy: none
		sourceColumn: Short Course

		annotation SummarizationSetBy = Automatic

	column 'Hole Number'
		dataType: int64
		formatString: 0
		lineageTag: 054433f8-14f7-4013-b6f2-704525dbcb57
		summarizeBy: sum
		sourceColumn: Hole Number

		annotation SummarizationSetBy = Automatic

	column 'Fairway % by Hole'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 876e1d98-91e3-4846-8b16-eebd20b5902a
		summarizeBy: none
		sourceColumn: Fairway % by Hole

		annotation SummarizationSetBy = User

	column Golfer
		dataType: string
		lineageTag: f128b29f-1b5b-4f84-af13-176321194b41
		summarizeBy: none
		sourceColumn: Golfer

		annotation SummarizationSetBy = Automatic

	column FairwayHitFlg
		dataType: int64
		formatString: 0
		lineageTag: 260d5424-0c4d-424c-9fc9-89f0301c2761
		summarizeBy: sum
		sourceColumn: FairwayHitFlg

		annotation SummarizationSetBy = Automatic

	column 'Fairway %'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 989a190a-b526-4dad-b8dd-acf7f9e799c7
		summarizeBy: sum
		sourceColumn: Fairway %

		annotation SummarizationSetBy = Automatic

	partition 'Fairway Log' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Owner\Desktop\Tyler\OneDrive\Projects\Golf Stats\data\raw\Golf Stats.xlsx"), null, true),
				    #"Fairway Log_Sheet" = Source{[Item="Fairway Log",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Fairway Log_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type any}, {"Course", type text}, {"Fairways", type any}, {"Hole 1", type any}, {"Hole 2", type any}, {"Hole 3", type any}, {"Hole 4", type any}, {"Hole 5", type any}, {"Hole 6", type any}, {"Hole 7", type any}, {"Hole 8", type any}, {"Hole 9", type any}, {"Hole 10", type any}, {"Hole 11", type any}, {"Hole 12", type any}, {"Hole 13", type any}, {"Hole 14", type any}, {"Hole 15", type any}, {"Hole 16", type any}, {"Hole 17", type any}, {"Hole 18", type any}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type",3),
				    #"Removed Blank Rows" = Table.SelectRows(#"Removed Bottom Rows", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Unpivoted Only Selected Columns" = Table.Unpivot(#"Removed Blank Rows", {"Hole 1", "Hole 2", "Hole 3", "Hole 4", "Hole 5", "Hole 6", "Hole 7", "Hole 8", "Hole 9", "Hole 10", "Hole 11", "Hole 12", "Hole 13", "Hole 14", "Hole 15", "Hole 16", "Hole 17", "Hole 18"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Only Selected Columns",{{"Attribute", "Hole"}, {"Value", "Fairway Score"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Hole Number", each Number.FromText(Text.Replace([Hole], "Hole ", ""))),
				    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "CourseHoleKey", each [Course] & " " & [Hole]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1","RoundKey",each [Golfer] & " - " & Text.From(Date.From([Date])) & " - " & [Course]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Hole Number", each Number.From(Text.Middle([Hole], 5))),
				    #"Duplicated Column" = Table.DuplicateColumn(#"Added Custom3", "Course", "Course - Copy"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Duplicated Column",{"Date", "Course", "Course - Copy", "Fairways", "Hole", "Fairway Score", "CourseHoleKey", "RoundKey", "Hole Number"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Course - Copy", "Short Course"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns1","Wailea Golf Club Emerald Course","Wailea Emerald",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Wailea Golf Club Gold Course","Wailea Gold",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Ka'anapali Golf Resort Royal Course","Ka'anapali Royal",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Brentwood Country Club","Brentwood",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value4" = Table.ReplaceValue(#"Replaced Value3","Sebonack Golf Club","Sebonack",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value5" = Table.ReplaceValue(#"Replaced Value4","Wind Watch Hamlet Course","Wind Watch",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value6" = Table.ReplaceValue(#"Replaced Value5","Middle Island Country Club - Oak and Spruce","Middle Island",Replacer.ReplaceText,{"Short Course"}),
				    #"Sorted Rows" = Table.Sort(#"Replaced Value6",{{"Short Course", Order.Descending}}),
				    #"Replaced Value7" = Table.ReplaceValue(#"Sorted Rows","Willow Creek Hamlet Course","Willow Creek",Replacer.ReplaceText,{"Short Course"}),
				    #"Replaced Value8" = Table.ReplaceValue(#"Replaced Value7","Spring Lake Thunderbird","Spring Lake",Replacer.ReplaceText,{"Short Course"}),
				    #"Sorted Rows1" = Table.Sort(#"Replaced Value8",{{"Date", Order.Descending}}),
				    #"Added Custom4" = Table.AddColumn(#"Sorted Rows1", "Custom", each if List.Contains({"←","→","↓","↑","0"}, [Fairway Score]) then 0 else 1),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom4",{{"Custom", Percentage.Type}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Custom", "Fairway % by Hole"}}),
				    #"Sorted Rows2" = Table.Sort(#"Renamed Columns2",{{"Date", Order.Descending}}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Sorted Rows2",{{"Date", type date}, {"Fairways", Int64.Type}, {"Fairway Score", type any}, {"CourseHoleKey", type text}, {"RoundKey", type text}, {"Hole Number", Int64.Type}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type2", "FairwayHitFlg", each if Text.Trim(Text.From([Fairway Score])) = "1" then 1 
				else if [Fairway Score] = null then null 
				else 0),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Added Custom5",{"Golfer", "Date", "Course", "Short Course", "Fairways", "Hole", "Fairway Score", "FairwayHitFlg", "CourseHoleKey", "RoundKey", "Hole Number", "Fairway % by Hole"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Reordered Columns1",{{"FairwayHitFlg", Int64.Type}, {"Fairway %", Percentage.Type}})
				in
				    #"Changed Type3"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

